<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.9">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MSSC 6250 – ex3-9</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="MSSC 6250">
<meta property="og:site_name" content="MSSC 6250">
<meta name="twitter:title" content="MSSC 6250">
<meta name="twitter:image" content="https://tinyurl.com/SML-MU/hw/sol/images/twitter-card.png">
<meta name="twitter:creator" content="@mmadoliat">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/mmadoliat/SML-s26/" title="GitHub organization" class="quarto-navigation-tool px-1" aria-label="GitHub organization"><i class="bi bi-github"></i></a>
    <a href="https://tinyurl.com/SML-MU" title="TinyURL" class="quarto-navigation-tool px-1" aria-label="TinyURL"><i class="bi bi-code-square"></i></a>
    <a href="https://d2l.mu.edu/" title="D2L" class="quarto-navigation-tool px-1" aria-label="D2L"><i class="bi bi-person-fill"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Useful links</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">HW</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../hw/HW 1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HW 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../hw/sol/HW1-sol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HW 1 Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../hw/HW 2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HW 2</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Computing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../computing/computing-cheatsheets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cheatsheets</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercise-3.9" id="toc-exercise-3.9" class="nav-link active" data-scroll-target="#exercise-3.9">Exercise 3.9</a>
  <ul class="collapse">
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">(a)</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">(b)</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">(c)</a></li>
  <li><a href="#i" id="toc-i" class="nav-link" data-scroll-target="#i">i</a></li>
  <li><a href="#ii" id="toc-ii" class="nav-link" data-scroll-target="#ii">ii</a></li>
  <li><a href="#iii" id="toc-iii" class="nav-link" data-scroll-target="#iii">iii</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">(d)</a>
  <ul class="collapse">
  <li><a href="#residuals-against-fitted-values" id="toc-residuals-against-fitted-values" class="nav-link" data-scroll-target="#residuals-against-fitted-values">Residuals against fitted values</a></li>
  <li><a href="#normal-q-q-plot" id="toc-normal-q-q-plot" class="nav-link" data-scroll-target="#normal-q-q-plot">Normal Q-Q plot</a></li>
  <li><a href="#scale-location-plot-of-sqrtresiduals-against-fitted-values" id="toc-scale-location-plot-of-sqrtresiduals-against-fitted-values" class="nav-link" data-scroll-target="#scale-location-plot-of-sqrtresiduals-against-fitted-values">Scale-Location plot of sqrt(|residuals|) against fitted values</a></li>
  <li><a href="#residuals-against-leverages" id="toc-residuals-against-leverages" class="nav-link" data-scroll-target="#residuals-against-leverages">Residuals against leverages</a></li>
  </ul></li>
  <li><a href="#comments" id="toc-comments" class="nav-link" data-scroll-target="#comments">Comments</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#e" id="toc-e" class="nav-link" data-scroll-target="#e">(e)</a></li>
  <li><a href="#f" id="toc-f" class="nav-link" data-scroll-target="#f">(f)</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/mmadoliat/SML-s26/edit/main/hw/sol/ex3-9.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/mmadoliat/SML-s26/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">




<section id="exercise-3.9" class="level1">
<h1>Exercise 3.9</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(style<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">'seaborn-white'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'../data/Auto.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'../data/Auto.csv'</span>, na_values<span class="op">=</span><span class="st">'?'</span>).dropna()</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small">
<thead>
<tr>
<th>
</th>
<th>
mpg
</th>
<th>
cylinders
</th>
<th>
displacement
</th>
<th>
horsepower
</th>
<th>
weight
</th>
<th>
acceleration
</th>
<th>
year
</th>
<th>
origin
</th>
<th>
name
</th>
</tr>
</thead>
<tbody>
<tr>
<th>
0
</th>
<td>
18.0
</td>
<td>
8
</td>
<td>
307.0
</td>
<td>
130.0
</td>
<td>
3504
</td>
<td>
12.0
</td>
<td>
70
</td>
<td>
1
</td>
<td>
chevrolet chevelle malibu
</td>
</tr>
<tr>
<th>
1
</th>
<td>
15.0
</td>
<td>
8
</td>
<td>
350.0
</td>
<td>
165.0
</td>
<td>
3693
</td>
<td>
11.5
</td>
<td>
70
</td>
<td>
1
</td>
<td>
buick skylark 320
</td>
</tr>
<tr>
<th>
2
</th>
<td>
18.0
</td>
<td>
8
</td>
<td>
318.0
</td>
<td>
150.0
</td>
<td>
3436
</td>
<td>
11.0
</td>
<td>
70
</td>
<td>
1
</td>
<td>
plymouth satellite
</td>
</tr>
<tr>
<th>
3
</th>
<td>
16.0
</td>
<td>
8
</td>
<td>
304.0
</td>
<td>
150.0
</td>
<td>
3433
</td>
<td>
12.0
</td>
<td>
70
</td>
<td>
1
</td>
<td>
amc rebel sst
</td>
</tr>
<tr>
<th>
4
</th>
<td>
17.0
</td>
<td>
8
</td>
<td>
302.0
</td>
<td>
140.0
</td>
<td>
3449
</td>
<td>
10.5
</td>
<td>
70
</td>
<td>
1
</td>
<td>
ford torino
</td>
</tr>
</tbody>
</table>
</div>
<section id="a" class="level2">
<h2 class="anchored" data-anchor-id="a">(a)</h2>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># http://seaborn.pydata.org/generated/seaborn.PairGrid.html</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> sns.PairGrid(df, diag_sharey<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>g.map_lower(sns.kdeplot, cmap<span class="op">=</span><span class="st">"Blues_d"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>g.map_upper(plt.scatter)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>g.map_diag(sns.kdeplot, lw<span class="op">=</span><span class="dv">3</span>, legend<span class="op">=</span><span class="va">False</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_09_files/03_09_4_0.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
</section>
<section id="b" class="level2">
<h2 class="anchored" data-anchor-id="b">(b)</h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pandas' corr() function takes care of excluding non numeric data: </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># https://github.com/pandas-dev/pandas/blob/v0.19.2/pandas/core/frame.py#L4721</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>df.corr()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

<table class="dataframe table table-sm table-striped small">
<thead>
<tr>
<th>
</th>
<th>
mpg
</th>
<th>
cylinders
</th>
<th>
displacement
</th>
<th>
horsepower
</th>
<th>
weight
</th>
<th>
acceleration
</th>
<th>
year
</th>
<th>
origin
</th>
</tr>
</thead>
<tbody>
<tr>
<th>
mpg
</th>
<td>
1.000000
</td>
<td>
-0.777618
</td>
<td>
-0.805127
</td>
<td>
-0.778427
</td>
<td>
-0.832244
</td>
<td>
0.423329
</td>
<td>
0.580541
</td>
<td>
0.565209
</td>
</tr>
<tr>
<th>
cylinders
</th>
<td>
-0.777618
</td>
<td>
1.000000
</td>
<td>
0.950823
</td>
<td>
0.842983
</td>
<td>
0.897527
</td>
<td>
-0.504683
</td>
<td>
-0.345647
</td>
<td>
-0.568932
</td>
</tr>
<tr>
<th>
displacement
</th>
<td>
-0.805127
</td>
<td>
0.950823
</td>
<td>
1.000000
</td>
<td>
0.897257
</td>
<td>
0.932994
</td>
<td>
-0.543800
</td>
<td>
-0.369855
</td>
<td>
-0.614535
</td>
</tr>
<tr>
<th>
horsepower
</th>
<td>
-0.778427
</td>
<td>
0.842983
</td>
<td>
0.897257
</td>
<td>
1.000000
</td>
<td>
0.864538
</td>
<td>
-0.689196
</td>
<td>
-0.416361
</td>
<td>
-0.455171
</td>
</tr>
<tr>
<th>
weight
</th>
<td>
-0.832244
</td>
<td>
0.897527
</td>
<td>
0.932994
</td>
<td>
0.864538
</td>
<td>
1.000000
</td>
<td>
-0.416839
</td>
<td>
-0.309120
</td>
<td>
-0.585005
</td>
</tr>
<tr>
<th>
acceleration
</th>
<td>
0.423329
</td>
<td>
-0.504683
</td>
<td>
-0.543800
</td>
<td>
-0.689196
</td>
<td>
-0.416839
</td>
<td>
1.000000
</td>
<td>
0.290316
</td>
<td>
0.212746
</td>
</tr>
<tr>
<th>
year
</th>
<td>
0.580541
</td>
<td>
-0.345647
</td>
<td>
-0.369855
</td>
<td>
-0.416361
</td>
<td>
-0.309120
</td>
<td>
0.290316
</td>
<td>
1.000000
</td>
<td>
0.181528
</td>
</tr>
<tr>
<th>
origin
</th>
<td>
0.565209
</td>
<td>
-0.568932
</td>
<td>
-0.614535
</td>
<td>
-0.455171
</td>
<td>
-0.585005
</td>
<td>
0.212746
</td>
<td>
0.181528
</td>
<td>
1.000000
</td>
</tr>
</tbody>
</table>
</div>
<p><strong>Extra</strong></p>
<p>Why not a correlation heatmap as well?</p>
<p><a href="http://seaborn.pydata.org/examples/network_correlations.html">http://seaborn.pydata.org/examples/network_correlations.html</a></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>corrmat <span class="op">=</span> df.corr()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up the matplotlib figure</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">9</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw the heatmap using seaborn</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>sns.heatmap(corrmat, vmax<span class="op">=</span><span class="fl">.8</span>, square<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>f.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_09_files/03_09_8_0.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
</section>
<section id="c" class="level2">
<h2 class="anchored" data-anchor-id="c">(c)</h2>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>reg <span class="op">=</span> smf.ols(<span class="st">'mpg ~ cylinders + displacement + horsepower + weight + acceleration + year + origin'</span>, df).fit()</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>reg.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<pre><code>     &lt;td&gt;mpg&lt;/td&gt;       &lt;th&gt;  R-squared:         &lt;/th&gt; &lt;td&gt;   0.821&lt;/td&gt; </code></pre><pre><code>             &lt;td&gt;OLS&lt;/td&gt;       &lt;th&gt;  Adj. R-squared:    &lt;/th&gt; &lt;td&gt;   0.818&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Least Squares&lt;/td&gt;  &lt;th&gt;  F-statistic:       &lt;/th&gt; &lt;td&gt;   252.4&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Fri, 08 Dec 2017&lt;/td&gt; &lt;th&gt;  Prob (F-statistic):&lt;/th&gt; &lt;td&gt;2.04e-139&lt;/td&gt;</code></pre><pre><code>           &lt;td&gt;09:49:08&lt;/td&gt;     &lt;th&gt;  Log-Likelihood:    &lt;/th&gt; &lt;td&gt; -1023.5&lt;/td&gt; </code></pre><pre><code>&lt;td&gt;   392&lt;/td&gt;      &lt;th&gt;  AIC:               &lt;/th&gt; &lt;td&gt;   2063.&lt;/td&gt; </code></pre><pre><code>    &lt;td&gt;   384&lt;/td&gt;      &lt;th&gt;  BIC:               &lt;/th&gt; &lt;td&gt;   2095.&lt;/td&gt; </code></pre><pre><code>        &lt;td&gt;     7&lt;/td&gt;      &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><pre><code>&lt;td&gt;nonrobust&lt;/td&gt;    &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><table class="simpletable">
<caption>
OLS Regression Results
</caption>
<tbody><tr>
<th>
Dep. Variable:
</th>

</tr>
<tr>
<th>
Model:
</th>

</tr>
<tr>
<th>
Method:
</th>

</tr>
<tr>
<th>
Date:
</th>

</tr>
<tr>
<th>
Time:
</th>

</tr>
<tr>
<th>
No.&nbsp;Observations:
</th>

</tr>
<tr>
<th>
Df Residuals:
</th>

</tr>
<tr>
<th>
Df Model:
</th>

</tr>
<tr>
<th>
Covariance Type:
</th>

</tr>
</tbody></table>
<pre><code> &lt;td&gt;   -0.0065&lt;/td&gt; &lt;td&gt;    0.001&lt;/td&gt; &lt;td&gt;   -9.929&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;   -0.008&lt;/td&gt; &lt;td&gt;   -0.005&lt;/td&gt;</code></pre><pre><code>   &lt;td&gt;    0.7508&lt;/td&gt; &lt;td&gt;    0.051&lt;/td&gt; &lt;td&gt;   14.729&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.651&lt;/td&gt; &lt;td&gt;    0.851&lt;/td&gt;</code></pre><pre><code> &lt;td&gt;    1.4261&lt;/td&gt; &lt;td&gt;    0.278&lt;/td&gt; &lt;td&gt;    5.127&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.879&lt;/td&gt; &lt;td&gt;    1.973&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<td>
</td>
<th>
coef
</th>
<th>
std err
</th>
<th>
t
</th>
<th>
P&gt;|t|
</th>
<th>
[0.025]
</th>
</tr>
<tr>
<th>
Intercept
</th>
<td>
-17.2184
</td>
<td>
4.644
</td>
<td>
-3.707
</td>
<td>
0.000
</td>
<td>
-26.350
</td>
<td>
-8.087
</td>
</tr>
<tr>
<th>
cylinders
</th>
<td>
-0.4934
</td>
<td>
0.323
</td>
<td>
-1.526
</td>
<td>
0.128
</td>
<td>
-1.129
</td>
<td>
0.142
</td>
</tr>
<tr>
<th>
displacement
</th>
<td>
0.0199
</td>
<td>
0.008
</td>
<td>
2.647
</td>
<td>
0.008
</td>
<td>
0.005
</td>
<td>
0.035
</td>
</tr>
<tr>
<th>
horsepower
</th>
<td>
-0.0170
</td>
<td>
0.014
</td>
<td>
-1.230
</td>
<td>
0.220
</td>
<td>
-0.044
</td>
<td>
0.010
</td>
</tr>
<tr>
<th>
weight
</th>

</tr>
<tr>
<th>
acceleration
</th>
<td>
0.0806
</td>
<td>
0.099
</td>
<td>
0.815
</td>
<td>
0.415
</td>
<td>
-0.114
</td>
<td>
0.275
</td>
</tr>
<tr>
<th>
year
</th>

</tr>
<tr>
<th>
origin
</th>

</tr>
</tbody></table>
<pre><code> &lt;td&gt;31.906&lt;/td&gt; &lt;th&gt;  Durbin-Watson:     &lt;/th&gt; &lt;td&gt;   1.309&lt;/td&gt;</code></pre><pre><code>    &lt;td&gt; 0.529&lt;/td&gt; &lt;th&gt;  Prob(JB):          &lt;/th&gt; &lt;td&gt;2.95e-12&lt;/td&gt;</code></pre><pre><code>&lt;td&gt; 4.460&lt;/td&gt; &lt;th&gt;  Cond. No.          &lt;/th&gt; &lt;td&gt;8.59e+04&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<th>
Omnibus:
</th>

</tr>
<tr>
<th>
Prob(Omnibus):
</th>
<td>
0.000
</td>
<th>
Jarque-Bera (JB):
</th>
<td>
53.100
</td>
</tr>
<tr>
<th>
Skew:
</th>

</tr>
<tr>
<th>
Kurtosis:
</th>

</tr>
</tbody></table>
</div>
</section>
<section id="i" class="level2">
<h2 class="anchored" data-anchor-id="i">i</h2>
<p>Yes, there is a relationship between the predictors and the response. In the table above we can see that the value of the F-statistic is 252 which is much larger than 1, so we can reject the corresponding null hypothesis:</p>
<p><span class="math display">\[
H_0 :\beta_{cylinders} = \beta_{displacement} = \beta_{weight} = \beta_{acceleration} = \beta_{year} = \beta_{origin}  =0.  
\]</span></p>
<p>In fact, the probability this data would be generated if <span class="math inline">\(H_0\)</span> was true is <span class="math inline">\(Prob(F-Statistic) = 2 \times 10^{-139}\)</span>, a ridiculously low value.</p>
</section>
<section id="ii" class="level2">
<h2 class="anchored" data-anchor-id="ii">ii</h2>
<p>We can see which predictors have a statistically significant relationship with the response by looking at the p-values in the table above. The predictors that have a statistically significant relationship to the response are definitely weight, year and origin, and we could say displacement as well; while cylinders, horsepower, and acceleration do not.</p>
</section>
<section id="iii" class="level2">
<h2 class="anchored" data-anchor-id="iii">iii</h2>
<p>The coefficient suggests that, on average, when the other variables are held constant, an increase of one year (of production) corresponds to an increase of 0.75 of mpg (so, the more recent the more efficient).</p>
</section>
<section id="d" class="level2">
<h2 class="anchored" data-anchor-id="d">(d)</h2>
<p>In R [4], by default, plot() on a fit produces 4 plots: * a plot of residuals against fitted values, * a Scale-Location plot of sqrt(| residuals |) against fitted values, * a Normal Q-Q plot, * a plot of residuals against leverages.</p>
<p>Below, we plot each of these 4 plots. We use the code published by Emre Can [5] with a few adaptations.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.gofplots <span class="im">import</span> ProbPlot</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">'seaborn'</span>) <span class="co"># pretty matplotlib plots</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>plt.rc(<span class="st">'font'</span>, size<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>plt.rc(<span class="st">'figure'</span>, titlesize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>plt.rc(<span class="st">'axes'</span>, labelsize<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>plt.rc(<span class="st">'axes'</span>, titlesize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>model_f <span class="op">=</span> <span class="st">'mpg ~ cylinders + </span><span class="ch">\</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="st">                 displacement + </span><span class="ch">\</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="st">                 horsepower + </span><span class="ch">\</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="st">                 weight + </span><span class="ch">\</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="st">                 acceleration + </span><span class="ch">\</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="st">                 year + </span><span class="ch">\</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="st">                 origin'</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>df.reset_index(drop<span class="op">=</span><span class="va">True</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(formula<span class="op">=</span>model_f, data<span class="op">=</span>df)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>model_fit <span class="op">=</span> model.fit()</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a><span class="co"># fitted values (need a constant term for intercept)</span></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>model_fitted_y <span class="op">=</span> model_fit.fittedvalues</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a><span class="co"># model residuals</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>model_residuals <span class="op">=</span> model_fit.resid</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a><span class="co"># normalized residuals</span></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>model_norm_residuals <span class="op">=</span> model_fit.get_influence().resid_studentized_internal</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a><span class="co"># absolute squared normalized residuals</span></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>model_norm_residuals_abs_sqrt <span class="op">=</span> np.sqrt(np.<span class="bu">abs</span>(model_norm_residuals))</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a><span class="co"># absolute residuals</span></span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>model_abs_resid <span class="op">=</span> np.<span class="bu">abs</span>(model_residuals)</span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a><span class="co"># leverage, from statsmodels internals</span></span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a>model_leverage <span class="op">=</span> model_fit.get_influence().hat_matrix_diag</span>
<span id="cb22-41"><a href="#cb22-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-42"><a href="#cb22-42" aria-hidden="true" tabindex="-1"></a><span class="co"># cook's distance, from statsmodels internals</span></span>
<span id="cb22-43"><a href="#cb22-43" aria-hidden="true" tabindex="-1"></a>model_cooks <span class="op">=</span> model_fit.get_influence().cooks_distance[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="residuals-against-fitted-values" class="level3">
<h3 class="anchored" data-anchor-id="residuals-against-fitted-values">Residuals against fitted values</h3>
<div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>plot_lm_1 <span class="op">=</span> plt.figure(<span class="dv">1</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>plot_lm_1.set_figheight(<span class="dv">8</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>plot_lm_1.set_figwidth(<span class="dv">12</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>plot_lm_1.axes[<span class="dv">0</span>] <span class="op">=</span> sns.residplot(model_fitted_y, <span class="st">'mpg'</span>, data<span class="op">=</span>df,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>                                  lowess<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>                                  scatter_kws<span class="op">=</span>{<span class="st">'alpha'</span>: <span class="fl">0.5</span>},</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>                                  line_kws<span class="op">=</span>{<span class="st">'color'</span>: <span class="st">'red'</span>, <span class="st">'lw'</span>: <span class="dv">1</span>, <span class="st">'alpha'</span>: <span class="fl">0.8</span>})</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>plot_lm_1.axes[<span class="dv">0</span>].set_title(<span class="st">'Residuals vs Fitted'</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>plot_lm_1.axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Fitted values'</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>plot_lm_1.axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Residuals'</span>)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="co"># annotations</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>abs_resid <span class="op">=</span> model_abs_resid.sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>abs_resid_top_3 <span class="op">=</span> abs_resid[:<span class="dv">3</span>]</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> abs_resid_top_3.index:</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>    plot_lm_1.axes[<span class="dv">0</span>].annotate(i, </span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>                               xy<span class="op">=</span>(model_fitted_y[i], </span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>                                   model_residuals[i]))<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_09_files/03_09_21_0.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
</section>
<section id="normal-q-q-plot" class="level3">
<h3 class="anchored" data-anchor-id="normal-q-q-plot">Normal Q-Q plot</h3>
<div class="sourceCode" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>QQ <span class="op">=</span> ProbPlot(model_norm_residuals)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>plot_lm_2 <span class="op">=</span> QQ.qqplot(line<span class="op">=</span><span class="st">'45'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">'#4C72B0'</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>plot_lm_2.set_figheight(<span class="dv">8</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>plot_lm_2.set_figwidth(<span class="dv">12</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>plot_lm_2.axes[<span class="dv">0</span>].set_title(<span class="st">'Normal Q-Q'</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>plot_lm_2.axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Theoretical Quantiles'</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>plot_lm_2.axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Standardized Residuals'</span>)<span class="op">;</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co"># annotations</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>abs_norm_resid <span class="op">=</span> np.flip(np.argsort(np.<span class="bu">abs</span>(model_norm_residuals)), <span class="dv">0</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>abs_norm_resid_top_3 <span class="op">=</span> abs_norm_resid[:<span class="dv">3</span>]</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r, i <span class="kw">in</span> <span class="bu">enumerate</span>(abs_norm_resid_top_3):</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    plot_lm_2.axes[<span class="dv">0</span>].annotate(i, </span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>                               xy<span class="op">=</span>(np.flip(QQ.theoretical_quantiles, <span class="dv">0</span>)[r],</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>                                   model_norm_residuals[i]))<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_09_files/03_09_23_0.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
</section>
<section id="scale-location-plot-of-sqrtresiduals-against-fitted-values" class="level3">
<h3 class="anchored" data-anchor-id="scale-location-plot-of-sqrtresiduals-against-fitted-values">Scale-Location plot of sqrt(|residuals|) against fitted values</h3>
<div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>plot_lm_3 <span class="op">=</span> plt.figure(<span class="dv">3</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>plot_lm_3.set_figheight(<span class="dv">8</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>plot_lm_3.set_figwidth(<span class="dv">12</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>plt.scatter(model_fitted_y, model_norm_residuals_abs_sqrt, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>sns.regplot(model_fitted_y, model_norm_residuals_abs_sqrt, </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>            scatter<span class="op">=</span><span class="va">False</span>, </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>            ci<span class="op">=</span><span class="va">False</span>, </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>            lowess<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>            line_kws<span class="op">=</span>{<span class="st">'color'</span>: <span class="st">'red'</span>, <span class="st">'lw'</span>: <span class="dv">1</span>, <span class="st">'alpha'</span>: <span class="fl">0.8</span>})</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>plot_lm_3.axes[<span class="dv">0</span>].set_title(<span class="st">'Scale-Location'</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>plot_lm_3.axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Fitted values'</span>)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>plot_lm_3.axes[<span class="dv">0</span>].set_ylabel(<span class="st">'$\sqrt{|Standardized Residuals|}$'</span>)<span class="op">;</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> abs_norm_resid_top_3:</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    plot_lm_3.axes[<span class="dv">0</span>].annotate(i, </span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>                               xy<span class="op">=</span>(model_fitted_y[i], </span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>                                   model_norm_residuals_abs_sqrt[i]))<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_09_files/03_09_25_0.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
</section>
<section id="residuals-against-leverages" class="level3">
<h3 class="anchored" data-anchor-id="residuals-against-leverages">Residuals against leverages</h3>
<div class="sourceCode" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>plot_lm_4 <span class="op">=</span> plt.figure(<span class="dv">4</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>plot_lm_4.set_figheight(<span class="dv">8</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>plot_lm_4.set_figwidth(<span class="dv">12</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>plt.scatter(model_leverage, model_norm_residuals, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>sns.regplot(model_leverage, model_norm_residuals, </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>            scatter<span class="op">=</span><span class="va">False</span>, </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>            ci<span class="op">=</span><span class="va">False</span>, </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>            lowess<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>            line_kws<span class="op">=</span>{<span class="st">'color'</span>: <span class="st">'red'</span>, <span class="st">'lw'</span>: <span class="dv">1</span>, <span class="st">'alpha'</span>: <span class="fl">0.8</span>})</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>plot_lm_4.axes[<span class="dv">0</span>].set_xlim(<span class="dv">0</span>, <span class="fl">0.20</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>plot_lm_4.axes[<span class="dv">0</span>].set_ylim(<span class="op">-</span><span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>plot_lm_4.axes[<span class="dv">0</span>].set_title(<span class="st">'Residuals vs Leverage'</span>)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>plot_lm_4.axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Leverage'</span>)</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>plot_lm_4.axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Standardized Residuals'</span>)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co"># annotations</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>leverage_top_3 <span class="op">=</span> np.flip(np.argsort(model_cooks), <span class="dv">0</span>)[:<span class="dv">3</span>]</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> leverage_top_3:</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    plot_lm_4.axes[<span class="dv">0</span>].annotate(i, </span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>                               xy<span class="op">=</span>(model_leverage[i], </span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>                                   model_norm_residuals[i]))</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a><span class="co"># shenanigans for cook's distance contours</span></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> graph(formula, x_range, label<span class="op">=</span><span class="va">None</span>, ls<span class="op">=</span><span class="st">'-'</span>):</span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> x_range</span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> formula(x)</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, y, label<span class="op">=</span>label, lw<span class="op">=</span><span class="dv">1</span>, ls<span class="op">=</span>ls, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="bu">len</span>(model_fit.params) <span class="co"># number of model parameters</span></span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a>graph(<span class="kw">lambda</span> x: np.sqrt((<span class="fl">0.5</span> <span class="op">*</span> p <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> x)) <span class="op">/</span> x), </span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a>      np.linspace(<span class="fl">0.001</span>, <span class="fl">0.200</span>, <span class="dv">50</span>), </span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a>      <span class="st">'Cook</span><span class="ch">\'</span><span class="st">s distance = .5'</span>, ls<span class="op">=</span><span class="st">'--'</span>) <span class="co"># 0.5 line</span></span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a>graph(<span class="kw">lambda</span> x: np.sqrt((<span class="dv">1</span> <span class="op">*</span> p <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> x)) <span class="op">/</span> x), </span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a>      np.linspace(<span class="fl">0.001</span>, <span class="fl">0.200</span>, <span class="dv">50</span>), <span class="st">'Cook</span><span class="ch">\'</span><span class="st">s distance = 1'</span>, ls<span class="op">=</span><span class="st">':'</span>) <span class="co"># 1 line</span></span>
<span id="cb26-40"><a href="#cb26-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-41"><a href="#cb26-41" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">'upper right'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_09_files/03_09_27_0.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
</section>
</section>
<section id="comments" class="level2">
<h2 class="anchored" data-anchor-id="comments">Comments</h2>
<p>No, there are no unusually large outliers, as per the the scale log location. They are however skewedly distributed. The larger the fitted value, the larger the variance, since the spread of the residuals increases.</p>
<p>No, even though there is an observation (number 13) with higher leverage, it is still well within Cook’s 0.5 distance.</p>
<p>The normal qq-plot deviates at one extreme, which could indicate that there are other explanatory predictors that we are not considering (quadratic terms, for example). Additionally, the funnel shape of the residuals plot indicates heteroskedacity.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>[1] https://stat.ethz.ch/R-manual/R-devel/library/stats/html/plot.lm.html</p>
<p>[2] https://emredjan.github.io/blog/2017/07/11/emulating-r-plots-in-python/</p>
</section>
<section id="e" class="level2">
<h2 class="anchored" data-anchor-id="e">(e)</h2>
<p>Statsmodels uses patsy which is a “mini-language” inspired by R and S to describe statistical models. The symbols ‘:’ and ‘*’ have the same meaning as in R. Namely, a:b includes an interaction term between a and b, while a*b is shorthand for a + b + a:b, that is, it includes a and b as well.</p>
<p>References:</p>
<ul>
<li>http://patsy.readthedocs.io/en/latest/formulas.html</li>
<li>http://stackoverflow.com/questions/33050104/difference-between-the-interaction-and-term-for-formulas-in-statsmodels-ols</li>
<li>http://stackoverflow.com/questions/23672466/interaction-effects-in-patsy-with-patsy-dmatrices-giving-duplicate-columns-for</li>
</ul>
<p>So, which pairs of variables would we expect to interact, both a priori (from our interpretation of the meaning of these variables) and from the pairs plot?</p>
<p>Perhaps horsepower and year? What would this mean? It would mean that, for different years, varying horsepower has different effect on mpg. It seems plausible. We could also interpret it in the reverse order: for different values of horsepower, does varying year have a different effect on mpg? For example, does the change in mpg when varying year (i.e., the derivative dmpg/dyear), differ when holding horsepower at either 130 or 160?</p>
<p>Let’s find out.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>reg <span class="op">=</span> smf.ols(<span class="st">'mpg ~ horsepower*year + displacement + weight + origin'</span>, df).fit()</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>reg.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<pre><code>     &lt;td&gt;mpg&lt;/td&gt;       &lt;th&gt;  R-squared:         &lt;/th&gt; &lt;td&gt;   0.851&lt;/td&gt; </code></pre><pre><code>             &lt;td&gt;OLS&lt;/td&gt;       &lt;th&gt;  Adj. R-squared:    &lt;/th&gt; &lt;td&gt;   0.849&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Least Squares&lt;/td&gt;  &lt;th&gt;  F-statistic:       &lt;/th&gt; &lt;td&gt;   367.0&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Fri, 08 Dec 2017&lt;/td&gt; &lt;th&gt;  Prob (F-statistic):&lt;/th&gt; &lt;td&gt;7.51e-156&lt;/td&gt;</code></pre><pre><code>           &lt;td&gt;09:49:11&lt;/td&gt;     &lt;th&gt;  Log-Likelihood:    &lt;/th&gt; &lt;td&gt; -987.81&lt;/td&gt; </code></pre><pre><code>&lt;td&gt;   392&lt;/td&gt;      &lt;th&gt;  AIC:               &lt;/th&gt; &lt;td&gt;   1990.&lt;/td&gt; </code></pre><pre><code>    &lt;td&gt;   385&lt;/td&gt;      &lt;th&gt;  BIC:               &lt;/th&gt; &lt;td&gt;   2017.&lt;/td&gt; </code></pre><pre><code>        &lt;td&gt;     6&lt;/td&gt;      &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><pre><code>&lt;td&gt;nonrobust&lt;/td&gt;    &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><table class="simpletable">
<caption>
OLS Regression Results
</caption>
<tbody><tr>
<th>
Dep. Variable:
</th>

</tr>
<tr>
<th>
Model:
</th>

</tr>
<tr>
<th>
Method:
</th>

</tr>
<tr>
<th>
Date:
</th>

</tr>
<tr>
<th>
Time:
</th>

</tr>
<tr>
<th>
No.&nbsp;Observations:
</th>

</tr>
<tr>
<th>
Df Residuals:
</th>

</tr>
<tr>
<th>
Df Model:
</th>

</tr>
<tr>
<th>
Covariance Type:
</th>

</tr>
</tbody></table>
<pre><code> &lt;td&gt;  -96.6688&lt;/td&gt; &lt;td&gt;    9.667&lt;/td&gt; &lt;td&gt;  -10.000&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt; -115.675&lt;/td&gt; &lt;td&gt;  -77.663&lt;/td&gt;</code></pre><pre><code>&lt;td&gt;    0.7993&lt;/td&gt; &lt;td&gt;    0.092&lt;/td&gt; &lt;td&gt;    8.687&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.618&lt;/td&gt; &lt;td&gt;    0.980&lt;/td&gt;</code></pre><pre><code>      &lt;td&gt;    1.8179&lt;/td&gt; &lt;td&gt;    0.128&lt;/td&gt; &lt;td&gt;   14.221&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    1.567&lt;/td&gt; &lt;td&gt;    2.069&lt;/td&gt;</code></pre><pre><code>    &lt;td&gt;   -0.0054&lt;/td&gt; &lt;td&gt;    0.001&lt;/td&gt; &lt;td&gt;  -10.170&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;   -0.006&lt;/td&gt; &lt;td&gt;   -0.004&lt;/td&gt;</code></pre><pre><code>    &lt;td&gt;    1.1866&lt;/td&gt; &lt;td&gt;    0.253&lt;/td&gt; &lt;td&gt;    4.684&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.688&lt;/td&gt; &lt;td&gt;    1.685&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<td>
</td>
<th>
coef
</th>
<th>
std err
</th>
<th>
t
</th>
<th>
P&gt;|t|
</th>
<th>
[0.025]
</th>
</tr>
<tr>
<th>
Intercept
</th>

</tr>
<tr>
<th>
horsepower
</th>

</tr>
<tr>
<th>
year
</th>

</tr>
<tr>
<th>
horsepower:year
</th>
<td>
-0.0113
</td>
<td>
0.001
</td>
<td>
-8.977
</td>
<td>
0.000
</td>
<td>
-0.014
</td>
<td>
-0.009
</td>
</tr>
<tr>
<th>
displacement
</th>
<td>
0.0068
</td>
<td>
0.005
</td>
<td>
1.344
</td>
<td>
0.180
</td>
<td>
-0.003
</td>
<td>
0.017
</td>
</tr>
<tr>
<th>
weight
</th>

</tr>
<tr>
<th>
origin
</th>

</tr>
</tbody></table>
<pre><code> &lt;td&gt;21.932&lt;/td&gt; &lt;th&gt;  Durbin-Watson:     &lt;/th&gt; &lt;td&gt;   1.488&lt;/td&gt;</code></pre><pre><code>    &lt;td&gt; 0.411&lt;/td&gt; &lt;th&gt;  Prob(JB):          &lt;/th&gt; &lt;td&gt;6.60e-08&lt;/td&gt;</code></pre><pre><code>&lt;td&gt; 4.161&lt;/td&gt; &lt;th&gt;  Cond. No.          &lt;/th&gt; &lt;td&gt;5.60e+05&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<th>
Omnibus:
</th>

</tr>
<tr>
<th>
Prob(Omnibus):
</th>
<td>
0.000
</td>
<th>
Jarque-Bera (JB):
</th>
<td>
33.066
</td>
</tr>
<tr>
<th>
Skew:
</th>

</tr>
<tr>
<th>
Kurtosis:
</th>

</tr>
</tbody></table>
</div>
<p>From the value of the p-value of the coefficient of the interaction term between horsepower and year, it does seem like there is a statistically significant relationship between the response and horsepower:year.</p>
<p>With 7 factors, there will be a total of 21 interaction terms. For simplicity sake, we will exclude all the terms with cylinders and acceleration, leaving us with 10 interaction terms. Let’s try to fit a model with these terms - a total of 15 terms.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> <span class="st">'mpg ~ displacement + horsepower + origin + weight + year </span><span class="ch">\</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="st">               + displacement:horsepower + displacement:origin + displacement:weight + displacement:year </span><span class="ch">\</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="st">               + horsepower:origin + horsepower:weight + horsepower:year + origin:weight + origin:year + weight:year'</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>reg <span class="op">=</span> smf.ols(model, df).fit()</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>reg.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<pre><code>     &lt;td&gt;mpg&lt;/td&gt;       &lt;th&gt;  R-squared:         &lt;/th&gt; &lt;td&gt;   0.880&lt;/td&gt; </code></pre><pre><code>             &lt;td&gt;OLS&lt;/td&gt;       &lt;th&gt;  Adj. R-squared:    &lt;/th&gt; &lt;td&gt;   0.875&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Least Squares&lt;/td&gt;  &lt;th&gt;  F-statistic:       &lt;/th&gt; &lt;td&gt;   184.0&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Fri, 08 Dec 2017&lt;/td&gt; &lt;th&gt;  Prob (F-statistic):&lt;/th&gt; &lt;td&gt;1.09e-162&lt;/td&gt;</code></pre><pre><code>           &lt;td&gt;09:49:11&lt;/td&gt;     &lt;th&gt;  Log-Likelihood:    &lt;/th&gt; &lt;td&gt; -945.49&lt;/td&gt; </code></pre><pre><code>&lt;td&gt;   392&lt;/td&gt;      &lt;th&gt;  AIC:               &lt;/th&gt; &lt;td&gt;   1923.&lt;/td&gt; </code></pre><pre><code>    &lt;td&gt;   376&lt;/td&gt;      &lt;th&gt;  BIC:               &lt;/th&gt; &lt;td&gt;   1987.&lt;/td&gt; </code></pre><pre><code>        &lt;td&gt;    15&lt;/td&gt;      &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><pre><code>&lt;td&gt;nonrobust&lt;/td&gt;    &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><table class="simpletable">
<caption>
OLS Regression Results
</caption>
<tbody><tr>
<th>
Dep. Variable:
</th>

</tr>
<tr>
<th>
Model:
</th>

</tr>
<tr>
<th>
Method:
</th>

</tr>
<tr>
<th>
Date:
</th>

</tr>
<tr>
<th>
Time:
</th>

</tr>
<tr>
<th>
No.&nbsp;Observations:
</th>

</tr>
<tr>
<th>
Df Residuals:
</th>

</tr>
<tr>
<th>
Df Model:
</th>

</tr>
<tr>
<th>
Covariance Type:
</th>

</tr>
</tbody></table>
<pre><code>         &lt;td&gt;  -51.3746&lt;/td&gt; &lt;td&gt;   26.175&lt;/td&gt; &lt;td&gt;   -1.963&lt;/td&gt; &lt;td&gt; 0.050&lt;/td&gt; &lt;td&gt; -102.843&lt;/td&gt; &lt;td&gt;    0.093&lt;/td&gt;</code></pre><pre><code>      &lt;td&gt;   -0.1818&lt;/td&gt; &lt;td&gt;    0.120&lt;/td&gt; &lt;td&gt;   -1.521&lt;/td&gt; &lt;td&gt; 0.129&lt;/td&gt; &lt;td&gt;   -0.417&lt;/td&gt; &lt;td&gt;    0.053&lt;/td&gt;</code></pre><pre><code>        &lt;td&gt;    0.9485&lt;/td&gt; &lt;td&gt;    0.232&lt;/td&gt; &lt;td&gt;    4.089&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.492&lt;/td&gt; &lt;td&gt;    1.405&lt;/td&gt;</code></pre><pre><code>            &lt;td&gt;   -3.0637&lt;/td&gt; &lt;td&gt;    5.496&lt;/td&gt; &lt;td&gt;   -0.557&lt;/td&gt; &lt;td&gt; 0.578&lt;/td&gt; &lt;td&gt;  -13.871&lt;/td&gt; &lt;td&gt;    7.744&lt;/td&gt;</code></pre><pre><code>            &lt;td&gt;   -0.0174&lt;/td&gt; &lt;td&gt;    0.016&lt;/td&gt; &lt;td&gt;   -1.115&lt;/td&gt; &lt;td&gt; 0.265&lt;/td&gt; &lt;td&gt;   -0.048&lt;/td&gt; &lt;td&gt;    0.013&lt;/td&gt;</code></pre><pre><code>              &lt;td&gt;    1.3975&lt;/td&gt; &lt;td&gt;    0.328&lt;/td&gt; &lt;td&gt;    4.267&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.754&lt;/td&gt; &lt;td&gt;    2.042&lt;/td&gt;</code></pre><pre><code> &lt;td&gt;    0.0010&lt;/td&gt; &lt;td&gt;    0.001&lt;/td&gt; &lt;td&gt;    0.710&lt;/td&gt; &lt;td&gt; 0.478&lt;/td&gt; &lt;td&gt;   -0.002&lt;/td&gt; &lt;td&gt;    0.004&lt;/td&gt;</code></pre><pre><code> &lt;td&gt;   -0.0629&lt;/td&gt; &lt;td&gt;    0.020&lt;/td&gt; &lt;td&gt;   -3.104&lt;/td&gt; &lt;td&gt; 0.002&lt;/td&gt; &lt;td&gt;   -0.103&lt;/td&gt; &lt;td&gt;   -0.023&lt;/td&gt;</code></pre><pre><code> &lt;td&gt;-1.175e-05&lt;/td&gt; &lt;td&gt; 1.77e-05&lt;/td&gt; &lt;td&gt;   -0.664&lt;/td&gt; &lt;td&gt; 0.507&lt;/td&gt; &lt;td&gt;-4.65e-05&lt;/td&gt; &lt;td&gt;  2.3e-05&lt;/td&gt;</code></pre><pre><code>   &lt;td&gt;   -0.0114&lt;/td&gt; &lt;td&gt;    0.003&lt;/td&gt; &lt;td&gt;   -3.998&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;   -0.017&lt;/td&gt; &lt;td&gt;   -0.006&lt;/td&gt;</code></pre><pre><code>     &lt;td&gt;    0.0014&lt;/td&gt; &lt;td&gt;    0.001&lt;/td&gt; &lt;td&gt;    1.200&lt;/td&gt; &lt;td&gt; 0.231&lt;/td&gt; &lt;td&gt;   -0.001&lt;/td&gt; &lt;td&gt;    0.004&lt;/td&gt;</code></pre><pre><code>       &lt;td&gt;    0.0322&lt;/td&gt; &lt;td&gt;    0.069&lt;/td&gt; &lt;td&gt;    0.464&lt;/td&gt; &lt;td&gt; 0.643&lt;/td&gt; &lt;td&gt;   -0.104&lt;/td&gt; &lt;td&gt;    0.169&lt;/td&gt;</code></pre><pre><code>       &lt;td&gt; 7.438e-05&lt;/td&gt; &lt;td&gt;    0.000&lt;/td&gt; &lt;td&gt;    0.394&lt;/td&gt; &lt;td&gt; 0.694&lt;/td&gt; &lt;td&gt;   -0.000&lt;/td&gt; &lt;td&gt;    0.000&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<td>
</td>
<th>
coef
</th>
<th>
std err
</th>
<th>
t
</th>
<th>
P&gt;|t|
</th>
<th>
[0.025]
</th>
</tr>
<tr>
<th>
Intercept
</th>

</tr>
<tr>
<th>
displacement
</th>

</tr>
<tr>
<th>
horsepower
</th>

</tr>
<tr>
<th>
origin
</th>

</tr>
<tr>
<th>
weight
</th>

</tr>
<tr>
<th>
year
</th>

</tr>
<tr>
<th>
displacement:horsepower
</th>
<td>
-0.0001
</td>
<td>
0.000
</td>
<td>
-0.815
</td>
<td>
0.416
</td>
<td>
-0.000
</td>
<td>
0.000
</td>
</tr>
<tr>
<th>
displacement:origin
</th>
<td>
0.0282
</td>
<td>
0.013
</td>
<td>
2.172
</td>
<td>
0.030
</td>
<td>
0.003
</td>
<td>
0.054
</td>
</tr>
<tr>
<th>
displacement:weight
</th>
<td>
2.792e-05
</td>
<td>
5.99e-06
</td>
<td>
4.663
</td>
<td>
0.000
</td>
<td>
1.61e-05
</td>
<td>
3.97e-05
</td>
</tr>
<tr>
<th>
displacement:year
</th>

</tr>
<tr>
<th>
horsepower:origin
</th>

</tr>
<tr>
<th>
horsepower:weight
</th>

</tr>
<tr>
<th>
horsepower:year
</th>

</tr>
<tr>
<th>
origin:weight
</th>

</tr>
<tr>
<th>
origin:year
</th>

</tr>
<tr>
<th>
weight:year
</th>

</tr>
</tbody></table>
<pre><code> &lt;td&gt;52.658&lt;/td&gt; &lt;th&gt;  Durbin-Watson:     &lt;/th&gt; &lt;td&gt;   1.599&lt;/td&gt;</code></pre><pre><code>    &lt;td&gt; 0.710&lt;/td&gt; &lt;th&gt;  Prob(JB):          &lt;/th&gt; &lt;td&gt;9.61e-26&lt;/td&gt;</code></pre><pre><code>&lt;td&gt; 5.244&lt;/td&gt; &lt;th&gt;  Cond. No.          &lt;/th&gt; &lt;td&gt;1.81e+08&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<th>
Omnibus:
</th>

</tr>
<tr>
<th>
Prob(Omnibus):
</th>
<td>
0.000
</td>
<th>
Jarque-Bera (JB):
</th>
<td>
115.208
</td>
</tr>
<tr>
<th>
Skew:
</th>

</tr>
<tr>
<th>
Kurtosis:
</th>

</tr>
</tbody></table>
</div>
<p>These results indicate that the interactions that appear to be statistically significant are displacement:weight, horsepower:origin and horsepower:year. Interestingly, when these are considered the only first order terms that are statistically different are horsepower and year. By the hierarchy principle (page 89), we should nonetheless include all of the main effects (for more on this, see <a href="https://stats.stackexchange.com/questions/27724/do-all-interactions-terms-need-their-individual-terms-in-regression-model">these</a> answers).</p>
<p>We could also have a try at <a href="https://en.wikipedia.org/wiki/Interaction_%28statistics%29#Interaction_plots">interaction plots</a>, which are not covered in the book, but we will leave it as a <a href="https://en.wikipedia.org/wiki/Interaction_%28statistics%29#/media/File:GSS_sealevel_interaction.png">mention</a> only.</p>
</section>
<section id="f" class="level2">
<h2 class="anchored" data-anchor-id="f">(f)</h2>
<p>As an example, we fit the data with a model containing the transformations indicated for the variable horsepower, starting with <span class="math inline">\(X^2\)</span>.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>reg <span class="op">=</span> smf.ols(<span class="st">'mpg ~ horsepower + np.power(horsepower,2) + weight + year + origin'</span>, df).fit()</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>reg.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<pre><code>     &lt;td&gt;mpg&lt;/td&gt;       &lt;th&gt;  R-squared:         &lt;/th&gt; &lt;td&gt;   0.851&lt;/td&gt; </code></pre><pre><code>             &lt;td&gt;OLS&lt;/td&gt;       &lt;th&gt;  Adj. R-squared:    &lt;/th&gt; &lt;td&gt;   0.849&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Least Squares&lt;/td&gt;  &lt;th&gt;  F-statistic:       &lt;/th&gt; &lt;td&gt;   439.5&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Fri, 08 Dec 2017&lt;/td&gt; &lt;th&gt;  Prob (F-statistic):&lt;/th&gt; &lt;td&gt;7.11e-157&lt;/td&gt;</code></pre><pre><code>           &lt;td&gt;09:49:11&lt;/td&gt;     &lt;th&gt;  Log-Likelihood:    &lt;/th&gt; &lt;td&gt; -988.57&lt;/td&gt; </code></pre><pre><code>&lt;td&gt;   392&lt;/td&gt;      &lt;th&gt;  AIC:               &lt;/th&gt; &lt;td&gt;   1989.&lt;/td&gt; </code></pre><pre><code>    &lt;td&gt;   386&lt;/td&gt;      &lt;th&gt;  BIC:               &lt;/th&gt; &lt;td&gt;   2013.&lt;/td&gt; </code></pre><pre><code>        &lt;td&gt;     5&lt;/td&gt;      &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><pre><code>&lt;td&gt;nonrobust&lt;/td&gt;    &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><table class="simpletable">
<caption>
OLS Regression Results
</caption>
<tbody><tr>
<th>
Dep. Variable:
</th>

</tr>
<tr>
<th>
Model:
</th>

</tr>
<tr>
<th>
Method:
</th>

</tr>
<tr>
<th>
Date:
</th>

</tr>
<tr>
<th>
Time:
</th>

</tr>
<tr>
<th>
No.&nbsp;Observations:
</th>

</tr>
<tr>
<th>
Df Residuals:
</th>

</tr>
<tr>
<th>
Df Model:
</th>

</tr>
<tr>
<th>
Covariance Type:
</th>

</tr>
</tbody></table>
<pre><code>         &lt;td&gt;   -6.6457&lt;/td&gt; &lt;td&gt;    3.915&lt;/td&gt; &lt;td&gt;   -1.698&lt;/td&gt; &lt;td&gt; 0.090&lt;/td&gt; &lt;td&gt;  -14.343&lt;/td&gt; &lt;td&gt;    1.052&lt;/td&gt;</code></pre><pre><code>        &lt;td&gt;   -0.2441&lt;/td&gt; &lt;td&gt;    0.027&lt;/td&gt; &lt;td&gt;   -9.099&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;   -0.297&lt;/td&gt; &lt;td&gt;   -0.191&lt;/td&gt;</code></pre><pre><code>            &lt;td&gt;   -0.0044&lt;/td&gt; &lt;td&gt;    0.000&lt;/td&gt; &lt;td&gt;  -10.426&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;   -0.005&lt;/td&gt; &lt;td&gt;   -0.004&lt;/td&gt;</code></pre><pre><code>              &lt;td&gt;    0.7456&lt;/td&gt; &lt;td&gt;    0.046&lt;/td&gt; &lt;td&gt;   16.145&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.655&lt;/td&gt; &lt;td&gt;    0.836&lt;/td&gt;</code></pre><pre><code>            &lt;td&gt;    1.0465&lt;/td&gt; &lt;td&gt;    0.238&lt;/td&gt; &lt;td&gt;    4.405&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.579&lt;/td&gt; &lt;td&gt;    1.514&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<td>
</td>
<th>
coef
</th>
<th>
std err
</th>
<th>
t
</th>
<th>
P&gt;|t|
</th>
<th>
[0.025]
</th>
</tr>
<tr>
<th>
Intercept
</th>

</tr>
<tr>
<th>
horsepower
</th>

</tr>
<tr>
<th>
np.power(horsepower, 2)
</th>
<td>
0.0008
</td>
<td>
9.13e-05
</td>
<td>
9.170
</td>
<td>
0.000
</td>
<td>
0.001
</td>
<td>
0.001
</td>
</tr>
<tr>
<th>
weight
</th>

</tr>
<tr>
<th>
year
</th>

</tr>
<tr>
<th>
origin
</th>

</tr>
</tbody></table>
<pre><code> &lt;td&gt;21.819&lt;/td&gt; &lt;th&gt;  Durbin-Watson:     &lt;/th&gt; &lt;td&gt;   1.500&lt;/td&gt;</code></pre><pre><code>    &lt;td&gt; 0.414&lt;/td&gt; &lt;th&gt;  Prob(JB):          &lt;/th&gt; &lt;td&gt;9.00e-08&lt;/td&gt;</code></pre><pre><code>&lt;td&gt; 4.140&lt;/td&gt; &lt;th&gt;  Cond. No.          &lt;/th&gt; &lt;td&gt;4.10e+05&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<th>
Omnibus:
</th>

</tr>
<tr>
<th>
Prob(Omnibus):
</th>
<td>
0.000
</td>
<th>
Jarque-Bera (JB):
</th>
<td>
32.447
</td>
</tr>
<tr>
<th>
Skew:
</th>

</tr>
<tr>
<th>
Kurtosis:
</th>

</tr>
</tbody></table>
</div>
<div class="sourceCode" id="cb89"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure()</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>fitted <span class="op">=</span> reg.fittedvalues</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>sns.regplot(fitted, df.mpg <span class="op">-</span> fitted,  lowess<span class="op">=</span><span class="va">True</span>, line_kws<span class="op">=</span>{<span class="st">'color'</span>:<span class="st">'r'</span>, <span class="st">'lw'</span>:<span class="dv">1</span>})</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> fig.axes[<span class="dv">0</span>]</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>ax.axhline(color<span class="op">=</span><span class="st">"grey"</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Residuals vs Fitted Values"</span>)</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Fitted Values"</span>)</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Residuals"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_09_files/03_09_40_0.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
<p>It is clear that this quadratic term is statistically significant. Let’s try adding a logarithmic term as well.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>reg <span class="op">=</span> smf.ols(<span class="st">'mpg ~ horsepower + np.power(horsepower,2) + np.log(horsepower) + weight + year + origin'</span>, df).fit()</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>reg.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<pre><code>     &lt;td&gt;mpg&lt;/td&gt;       &lt;th&gt;  R-squared:         &lt;/th&gt; &lt;td&gt;   0.855&lt;/td&gt; </code></pre><pre><code>             &lt;td&gt;OLS&lt;/td&gt;       &lt;th&gt;  Adj. R-squared:    &lt;/th&gt; &lt;td&gt;   0.853&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Least Squares&lt;/td&gt;  &lt;th&gt;  F-statistic:       &lt;/th&gt; &lt;td&gt;   378.6&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Fri, 08 Dec 2017&lt;/td&gt; &lt;th&gt;  Prob (F-statistic):&lt;/th&gt; &lt;td&gt;4.62e-158&lt;/td&gt;</code></pre><pre><code>           &lt;td&gt;09:49:11&lt;/td&gt;     &lt;th&gt;  Log-Likelihood:    &lt;/th&gt; &lt;td&gt; -982.62&lt;/td&gt; </code></pre><pre><code>&lt;td&gt;   392&lt;/td&gt;      &lt;th&gt;  AIC:               &lt;/th&gt; &lt;td&gt;   1979.&lt;/td&gt; </code></pre><pre><code>    &lt;td&gt;   385&lt;/td&gt;      &lt;th&gt;  BIC:               &lt;/th&gt; &lt;td&gt;   2007.&lt;/td&gt; </code></pre><pre><code>        &lt;td&gt;     6&lt;/td&gt;      &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><pre><code>&lt;td&gt;nonrobust&lt;/td&gt;    &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><table class="simpletable">
<caption>
OLS Regression Results
</caption>
<tbody><tr>
<th>
Dep. Variable:
</th>

</tr>
<tr>
<th>
Model:
</th>

</tr>
<tr>
<th>
Method:
</th>

</tr>
<tr>
<th>
Date:
</th>

</tr>
<tr>
<th>
Time:
</th>

</tr>
<tr>
<th>
No.&nbsp;Observations:
</th>

</tr>
<tr>
<th>
Df Residuals:
</th>

</tr>
<tr>
<th>
Df Model:
</th>

</tr>
<tr>
<th>
Covariance Type:
</th>

</tr>
</tbody></table>
<pre><code>         &lt;td&gt;   80.3681&lt;/td&gt; &lt;td&gt;   25.568&lt;/td&gt; &lt;td&gt;    3.143&lt;/td&gt; &lt;td&gt; 0.002&lt;/td&gt; &lt;td&gt;   30.098&lt;/td&gt; &lt;td&gt;  130.638&lt;/td&gt;</code></pre><pre><code>        &lt;td&gt;    0.2570&lt;/td&gt; &lt;td&gt;    0.148&lt;/td&gt; &lt;td&gt;    1.737&lt;/td&gt; &lt;td&gt; 0.083&lt;/td&gt; &lt;td&gt;   -0.034&lt;/td&gt; &lt;td&gt;    0.548&lt;/td&gt;</code></pre><pre><code>&lt;td&gt;  -27.5412&lt;/td&gt; &lt;td&gt;    8.000&lt;/td&gt; &lt;td&gt;   -3.443&lt;/td&gt; &lt;td&gt; 0.001&lt;/td&gt; &lt;td&gt;  -43.270&lt;/td&gt; &lt;td&gt;  -11.812&lt;/td&gt;</code></pre><pre><code>            &lt;td&gt;   -0.0048&lt;/td&gt; &lt;td&gt;    0.000&lt;/td&gt; &lt;td&gt;  -11.098&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;   -0.006&lt;/td&gt; &lt;td&gt;   -0.004&lt;/td&gt;</code></pre><pre><code>              &lt;td&gt;    0.7561&lt;/td&gt; &lt;td&gt;    0.046&lt;/td&gt; &lt;td&gt;   16.565&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.666&lt;/td&gt; &lt;td&gt;    0.846&lt;/td&gt;</code></pre><pre><code>            &lt;td&gt;    0.9480&lt;/td&gt; &lt;td&gt;    0.236&lt;/td&gt; &lt;td&gt;    4.016&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.484&lt;/td&gt; &lt;td&gt;    1.412&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<td>
</td>
<th>
coef
</th>
<th>
std err
</th>
<th>
t
</th>
<th>
P&gt;|t|
</th>
<th>
[0.025]
</th>
</tr>
<tr>
<th>
Intercept
</th>

</tr>
<tr>
<th>
horsepower
</th>

</tr>
<tr>
<th>
np.power(horsepower, 2)
</th>
<td>
-0.0002
</td>
<td>
0.000
</td>
<td>
-0.571
</td>
<td>
0.568
</td>
<td>
-0.001
</td>
<td>
0.000
</td>
</tr>
<tr>
<th>
np.log(horsepower)
</th>

</tr>
<tr>
<th>
weight
</th>

</tr>
<tr>
<th>
year
</th>

</tr>
<tr>
<th>
origin
</th>

</tr>
</tbody></table>
<pre><code> &lt;td&gt;17.905&lt;/td&gt; &lt;th&gt;  Durbin-Watson:     &lt;/th&gt; &lt;td&gt;   1.575&lt;/td&gt;</code></pre><pre><code>    &lt;td&gt; 0.312&lt;/td&gt; &lt;th&gt;  Prob(JB):          &lt;/th&gt; &lt;td&gt;4.34e-07&lt;/td&gt;</code></pre><pre><code>&lt;td&gt; 4.185&lt;/td&gt; &lt;th&gt;  Cond. No.          &lt;/th&gt; &lt;td&gt;2.84e+06&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<th>
Omnibus:
</th>

</tr>
<tr>
<th>
Prob(Omnibus):
</th>
<td>
0.000
</td>
<th>
Jarque-Bera (JB):
</th>
<td>
29.299
</td>
</tr>
<tr>
<th>
Skew:
</th>

</tr>
<tr>
<th>
Kurtosis:
</th>

</tr>
</tbody></table>
</div>
<p>Now the p-value for the square term is very large. This indicates that there is indeed a non-linearity but it seems to be better captured by the logarithm than the square. Let’s try adding the square root term.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>reg <span class="op">=</span> smf.ols(<span class="st">'mpg ~ horsepower + np.power(horsepower,2) + np.log(horsepower) + np.sqrt(horsepower) + weight + year + origin'</span>, df).fit()</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>reg.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<pre><code>     &lt;td&gt;mpg&lt;/td&gt;       &lt;th&gt;  R-squared:         &lt;/th&gt; &lt;td&gt;   0.859&lt;/td&gt; </code></pre><pre><code>             &lt;td&gt;OLS&lt;/td&gt;       &lt;th&gt;  Adj. R-squared:    &lt;/th&gt; &lt;td&gt;   0.856&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Least Squares&lt;/td&gt;  &lt;th&gt;  F-statistic:       &lt;/th&gt; &lt;td&gt;   332.9&lt;/td&gt; </code></pre><pre><code>       &lt;td&gt;Fri, 08 Dec 2017&lt;/td&gt; &lt;th&gt;  Prob (F-statistic):&lt;/th&gt; &lt;td&gt;9.16e-159&lt;/td&gt;</code></pre><pre><code>           &lt;td&gt;09:49:12&lt;/td&gt;     &lt;th&gt;  Log-Likelihood:    &lt;/th&gt; &lt;td&gt; -977.89&lt;/td&gt; </code></pre><pre><code>&lt;td&gt;   392&lt;/td&gt;      &lt;th&gt;  AIC:               &lt;/th&gt; &lt;td&gt;   1972.&lt;/td&gt; </code></pre><pre><code>    &lt;td&gt;   384&lt;/td&gt;      &lt;th&gt;  BIC:               &lt;/th&gt; &lt;td&gt;   2004.&lt;/td&gt; </code></pre><pre><code>        &lt;td&gt;     7&lt;/td&gt;      &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><pre><code>&lt;td&gt;nonrobust&lt;/td&gt;    &lt;th&gt;                     &lt;/th&gt;     &lt;td&gt; &lt;/td&gt;    </code></pre><table class="simpletable">
<caption>
OLS Regression Results
</caption>
<tbody><tr>
<th>
Dep. Variable:
</th>

</tr>
<tr>
<th>
Model:
</th>

</tr>
<tr>
<th>
Method:
</th>

</tr>
<tr>
<th>
Date:
</th>

</tr>
<tr>
<th>
Time:
</th>

</tr>
<tr>
<th>
No.&nbsp;Observations:
</th>

</tr>
<tr>
<th>
Df Residuals:
</th>

</tr>
<tr>
<th>
Df Model:
</th>

</tr>
<tr>
<th>
Covariance Type:
</th>

</tr>
</tbody></table>
<pre><code>         &lt;td&gt; -426.3991&lt;/td&gt; &lt;td&gt;  167.288&lt;/td&gt; &lt;td&gt;   -2.549&lt;/td&gt; &lt;td&gt; 0.011&lt;/td&gt; &lt;td&gt; -755.314&lt;/td&gt; &lt;td&gt;  -97.485&lt;/td&gt;</code></pre><pre><code>        &lt;td&gt;    8.4452&lt;/td&gt; &lt;td&gt;    2.676&lt;/td&gt; &lt;td&gt;    3.156&lt;/td&gt; &lt;td&gt; 0.002&lt;/td&gt; &lt;td&gt;    3.184&lt;/td&gt; &lt;td&gt;   13.706&lt;/td&gt;</code></pre><pre><code>&lt;td&gt;  416.0064&lt;/td&gt; &lt;td&gt;  144.951&lt;/td&gt; &lt;td&gt;    2.870&lt;/td&gt; &lt;td&gt; 0.004&lt;/td&gt; &lt;td&gt;  131.009&lt;/td&gt; &lt;td&gt;  701.004&lt;/td&gt;</code></pre><pre><code>            &lt;td&gt;   -0.0048&lt;/td&gt; &lt;td&gt;    0.000&lt;/td&gt; &lt;td&gt;  -11.229&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;   -0.006&lt;/td&gt; &lt;td&gt;   -0.004&lt;/td&gt;</code></pre><pre><code>              &lt;td&gt;    0.7475&lt;/td&gt; &lt;td&gt;    0.045&lt;/td&gt; &lt;td&gt;   16.522&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.659&lt;/td&gt; &lt;td&gt;    0.836&lt;/td&gt;</code></pre><pre><code>            &lt;td&gt;    0.9088&lt;/td&gt; &lt;td&gt;    0.234&lt;/td&gt; &lt;td&gt;    3.886&lt;/td&gt; &lt;td&gt; 0.000&lt;/td&gt; &lt;td&gt;    0.449&lt;/td&gt; &lt;td&gt;    1.369&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<td>
</td>
<th>
coef
</th>
<th>
std err
</th>
<th>
t
</th>
<th>
P&gt;|t|
</th>
<th>
[0.025]
</th>
</tr>
<tr>
<th>
Intercept
</th>

</tr>
<tr>
<th>
horsepower
</th>

</tr>
<tr>
<th>
np.power(horsepower, 2)
</th>
<td>
-0.0060
</td>
<td>
0.002
</td>
<td>
-3.117
</td>
<td>
0.002
</td>
<td>
-0.010
</td>
<td>
-0.002
</td>
</tr>
<tr>
<th>
np.log(horsepower)
</th>

</tr>
<tr>
<th>
np.sqrt(horsepower)
</th>
<td>
-229.6161
</td>
<td>
74.927
</td>
<td>
-3.065
</td>
<td>
0.002
</td>
<td>
-376.934
</td>
<td>
-82.298
</td>
</tr>
<tr>
<th>
weight
</th>

</tr>
<tr>
<th>
year
</th>

</tr>
<tr>
<th>
origin
</th>

</tr>
</tbody></table>
<pre><code> &lt;td&gt;23.395&lt;/td&gt; &lt;th&gt;  Durbin-Watson:     &lt;/th&gt; &lt;td&gt;   1.570&lt;/td&gt;</code></pre><pre><code>    &lt;td&gt; 0.411&lt;/td&gt; &lt;th&gt;  Prob(JB):          &lt;/th&gt; &lt;td&gt;6.18e-09&lt;/td&gt;</code></pre><pre><code>&lt;td&gt; 4.281&lt;/td&gt; &lt;th&gt;  Cond. No.          &lt;/th&gt; &lt;td&gt;2.50e+07&lt;/td&gt;</code></pre><table class="simpletable">
<tbody><tr>
<th>
Omnibus:
</th>

</tr>
<tr>
<th>
Prob(Omnibus):
</th>
<td>
0.000
</td>
<th>
Jarque-Bera (JB):
</th>
<td>
37.804
</td>
</tr>
<tr>
<th>
Skew:
</th>

</tr>
<tr>
<th>
Kurtosis:
</th>

</tr>
</tbody></table>
</div>
<p>So now the square term is back to a small p-value, indicating that it is statistically significant in the presence of the square root and the logarithm.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2026, Mehdi Maadooliat</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/mmadoliat/SML-s26/edit/main/hw/sol/ex3-9.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/mmadoliat/SML-s26/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This page is built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>